"""alter_tenant_country_length

Revision ID: ab5830c6d421
Revises: 7f8bdd389265
Create Date: 2026-06-07 00:46:59.696074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ab5830c6d421'
down_revision: Union[str, None] = '7f8bdd389265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'country',
               existing_type=mysql.VARCHAR(length=2),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'country',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=2),
               existing_nullable=False)
    # ### end Alembic commands ###
