"""create_user_events_table

Revision ID: f977f6d434f7
Revises: bef0e472f0bf
Create Date: 2026-06-07 05:56:12.041991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f977f6d434f7'
down_revision: Union[str, None] = 'bef0e472f0bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keycloak_user_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('actor_sub', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_events_keycloak_user_id'), 'user_events', ['keycloak_user_id'], unique=False)
    op.create_index(op.f('ix_user_events_tenant_id'), 'user_events', ['tenant_id'], unique=False)
    # Note: tenants.products TEXT→JSON alter skipped — MySQL 5.6 does not support the JSON column type.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_events_tenant_id'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_keycloak_user_id'), table_name='user_events')
    op.drop_table('user_events')
    # ### end Alembic commands ###
